### ISSUE TITLE
0.18.0/master doesnt compile with rust 1.39

### ISSUE THREAD

**Issue by davidB** [clux/kube-rs#87]
When compiling with 0.18.0 as a dependency, or the current master branch of kube-rs I got the following error:

```sh
...
   Compiling reqwest v0.10.0-alpha.1
error[E0277]: the trait bound `futures_util::stream::peek::Peekable<async_impl::decoder::imp::IoStream>: futures_core::stream::Stream` is not satisfied
   --> /Users/d.bernard1/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.0-alpha.1/src/async_impl/response.rs:283:39
    |
283 |         if let Some(item) = self.body.next().await {
    |                                       ^^^^ the trait `futures_core::stream::Stream` is not implemented for `futures_util::stream::peek::Peekable<async_impl::decoder::imp::IoStream>`
    |
    = note: required because of the requirements on the impl of `std::marker::Unpin` for `async_compression::stream::GzipDecoder<futures_util::stream::peek::Peekable<async_impl::decoder::imp::IoStream>>`
    = note: required because it appears within the type `async_impl::decoder::imp::Inner`
    = note: required because it appears within the type `async_impl::decoder::imp::Decoder`

error[E0277]: the trait bound `futures_util::stream::peek::Peekable<async_impl::decoder::imp::IoStream>: futures_core::stream::Stream` is not satisfied
   --> /Users/d.bernard1/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.0-alpha.1/src/async_impl/response.rs:283:29
    |
283 |         if let Some(item) = self.body.next().await {
    |                             ^^^^^^^^^^^^^^^^^^^^^^ the trait `futures_core::stream::Stream` is not implemented for `futures_util::stream::peek::Peekable<async_impl::decoder::imp::IoStream>`
    |
    = note: required because of the requirements on the impl of `std::marker::Unpin` for `async_compression::stream::GzipDecoder<futures_util::stream::peek::Peekable<async_impl::decoder::imp::IoStream>>`
    = note: required because it appears within the type `async_impl::decoder::imp::Inner`
    = note: required because it appears within the type `async_impl::decoder::imp::Decoder`
    = note: required because of the requirements on the impl of `core::future::future::Future` for `futures_util::stream::next::Next<'_, async_impl::decoder::imp::Decoder>`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `reqwest`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by clux** [comment]
Uh, that's strange. I swear it compiled earlier on stable. I'll have a look later on.

**Comment by CarlosLanderas** [comment]
Im having exactly the same problem.

rustup 1.20.2 (13979c968 2019-10-16)

rustc 1.40.0-nightly (1423bec54 2019-11-05)
rustc 1.39.0 (4560ea788 2019-11-04)

It is not compiling in nightly or stable either.

Just using this dependencies and code:
```
[dependencies]
kube = "0.18.0"
serde = "1.0.102"
serde_json = "1.0.41"
serde_derive = "1.0.102"
```

```rust
use kube:: {
    api::{Object, Void, RawApi},
    client::APIClient,
    config
};

use k8s_controller::book::Book;

type Kubebook = Object<Book, Void>;

fn main() {

    let kubeconfig = config::load_kube_config().expect("kubeconfig failed to load");

    let client = APIClient::new(kube);

    let namespace = "default";

    let resource = RawApi::customResource("books")
        .group("example.technosophos.com")
        .with(&namespace);
}

```



```
error[E0277]: the trait bound `futures_util::stream::peek::Peekable<async_impl::decoder::imp::IoStream>: futures_core::stream::Stream` is not satisfied
   --> /home/clanderas/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.0-alpha.1/src/async_impl/response.rs:283:39
    |
283 |         if let Some(item) = self.body.next().await {
    |                                       ^^^^ the trait `futures_core::stream::Stream` is not implemented for `futures_util::stream::peek::Peekable<async_impl::decoder::imp::IoStream>`
    |
    = note: required because of the requirements on the impl of `std::marker::Unpin` for `async_compression::stream::GzipDecoder<futures_util::stream::peek::Peekable<async_impl::decoder::imp::IoStream>>`
    = note: required because it appears within the type `async_impl::decoder::imp::Inner`
    = note: required because it appears within the type `async_impl::decoder::imp::Decoder`

error[E0277]: the trait bound `futures_util::stream::peek::Peekable<async_impl::decoder::imp::IoStream>: futures_core::stream::Stream` is not satisfied
   --> /home/clanderas/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.0-alpha.1/src/async_impl/response.rs:283:29

```

**Comment by clux** [comment]
Confirmed, there is a cached dependency in my local `Cargo.lock`, and because I was waiting for circleci's official rustc 1.39.0 image, it went unnoticed. Trying to get to the bottom of it now.

**Comment by clux** [comment]
Seems to arise due to the `gzip` feature in reqwest. Possibly related to https://github.com/seanmonstar/reqwest/pull/703

**Comment by clux** [comment]
Released a fix in 0.18.1. Does turn off gzip for now though :/
